# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Natural Sort Project (CI included) |  © 2025 by HuuBng

on:
  push:
    branches: [ "main" ]
    paths:
      -  'C#/NaturalSortApp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore C#/NaturalSortApp/NaturalSortApp.sln
      - name: Build
        run: dotnet build C#/NaturalSortApp/NaturalSortApp.sln --no-restore
      - name: Test
        run: dotnet test C#/NaturalSortApp/NaturalSortApp.sln --no-build
